apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mw8m3ueqk-nodejs
  janus-idp.io/tekton: mw8m3ueqk-nodejs
  backstage.io/kubernetes-id: mw8m3ueqk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mw8m3ueqk-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
