apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mw8m3ueqk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mw8m3ueqk-nodejs 
  name: mw8m3ueqk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mw8m3ueqk-nodejs 
